steps:
# Run unit tests
- name: 'gcr.io/cloud-builders/go'
  args: ['install', '.']
  env: ['PROJECT_ROOT=github.com/pcman312/hackathon']
- name: 'gcr.io/cloud-builders/go:debian'
  args: ['test', '-v', '-race', './...']
  env: ['PROJECT_ROOT=github.com/pcman312/hackathon']
