version: '2.1'
services:
  elasticsearch:
    image: elasticsearch:2.4.6
    ports:
    - "9200:9200"
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health || exit 1"]
      interval: 1s
      timeout: 5s
      retries: 10
  hackathon:
    build:
      dockerfile: Dockerfile
      context: .
#      args:
#        build: "service"
    ports:
    - "9090:9090"
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
    - "elasticsearch"
  component-test:
    build:
      dockerfile: component_tests/Dockerfile
      context: .
#      args:
#        build: "component-tests"
    depends_on:
    - "hackathon"
    links:
    - "hackathon"